### PR TITLE
Extending map importer

### PR DESCRIPTION
**Pull request by swift502**
Hi!

Extending map importer functionality. Now you can choose from any of the Renderware GTAs.

As for LCS and VCS, I downloaded PC versions (SA conversion mods) for each game, which exposes the files in their usual format. It seems easier than extracting all the files from the PS2 / PSP versions of the games.

None of this is, of course,  properly tested 😄, so I might want to at least try and import a couple of IPLs from each game to make sure there's some basic functionality. So maybe don't pull this just yet. Or do, whatever's easier.

I also have ideas for categorizing imported objects better (props, LODs, etc.). Also I'd like to completely ditch the current object duplication, and instead represent every IPL entry with a collection instance empty. **That would be a purely 2.8 feature though.** The collection instancing alternative for Blender 2.7x would be group duplication, but as far as I recall, groups are a lot harder to work with and it would obviously require a bunch of extra work to keep everything compatible between 2.7x and 2.8x.

### CODE REVIEW

**Comment by swift502** [comment]
Wow, LCS and VCS used ["different" engine](https://www.grandtheftwiki.com/Leeds_Engine)?
I hope the dffs are pretty much the same. Especially in the SA mod versions of the games...

**Comment by ThePortuguesePlayer** [comment]
image

Tried to test it with a random SA IPL... Gives out this error message.

**Comment by swift502** [comment]
Yeah, like I said, I haven't tested it yet.
Apparently SA doesn't support object scaling like 3 and VC...

**Comment by ThePortuguesePlayer** [comment]
It now imported a GTASA IPL successfully.
Thank you!

**Comment by ThePortuguesePlayer** [comment]
image
It does not let me do some of them still.
SFw and VegasN still give out errors and stop importing so far.

**Comment by swift502** [comment]
Thanks a lot for the report! I'll look into it.

**Comment by Zarig** [comment]
Hey,

Good job with the pull request. I'll have a look at it in a while, have been a bit busy with some other projects. Also yeah, I don't plan on supporting 2.7x any more since the new version is now stable, so it's no problem to write 2.8 specific code.

Thanks.

**Comment by Blood-PawWerewolf** [comment]
> Thanks a lot for the report! I'll look into it.

I had the same issue with on older addon called “GTA Tools” and it ended up being the IPL having the “, “ as “ ,” in a few lines. It looks like somebody at Rockstar at the time either made those lines incorrectly or they were changed like that because they caused problems during development of the game and forgot to remove/fix them.

**Comment by swift502** [comment]
@Blood-PawWerewolf Wow, is it by any chance open source? I'd love not to repeat hard work someone else has already done.

**Comment by Blood-PawWerewolf** [comment]
> 
> 
> @Blood-PawWerewolf Wow, is it by any chance open source? I'd love to learn from it to not repeat the hard work you've already done.

all i had to do was open the IDE and IPL files in notepad++ and fix them, i‘m still making sure that they all work flawlessly, but yeah, i’ll release the fixed files. probably via mega or something since I’m pretty much sure i can’t share Rockstar’s files on Github due to them being the actual game files, just fixed up a bit.

**Comment by swift502** [comment]
@Blood-PawWerewolf Oh no I'm sure I'll figure that specific issue out.

I meant the project in general. It's not open sourced then?

**Comment by ThePortuguesePlayer** [comment]
From what I heard the addon is made by a Japanese guy and got translated by someone from a forum.
I also used GTA Tools and I can confirm those IPLs give errors while importing.
GTA Tools is actually a pretty good plugin, but not good enough for my specific needs.
It only works for 2.79.
If you Google "Blender GTA Tools", it will be the first result. The guy explains roughly where the addon came from.

**Comment by Blood-PawWerewolf** [comment]
> @Blood-PawWerewolf Oh no I'm sure I'll figure that specific issue out.
> 
> I meant the project in general. It's not open sourced then?

What project are talking about?

**Comment by swift502** [comment]
Continued in #26

**Pull request closed without merging**
